// packages/views/NewWindow.vue
<template>
    <div class="newContainer">
        <div id="newWindow" window-name="게임 속성" ref="newWindow">
            <ul>
                <li>
                    <label for="name">게임명 : </label
                    ><input type="text" placeholder="name" />
                </li>
                <li>
                    <label for="name">위치 : </label
                    ><input
                        type="file"
                        placeholder=""
                        webkitdirectory
                        directory
                        multiple
                    />
                </li>
                <li>
                    <label for="name">작성자 명 : </label
                    ><input type="text" placeholder="" />
                </li>
            </ul>
            <div class="newWindow__control-box">
                <p>
                    <span
                        ><i
                            class="far fa-window-close"
                            id="action-close"
                            @click="close"
                        ></i
                    ></span>
                </p>
            </div>
            <div class="panel">
                <button><i class="fas fa-upload"></i>프로젝트 생성</button>
            </div>
        </div>
    </div>
</template>
<script>
export default {
    mounted() {
        $(this.$refs.newWindow).draggable();
    },
    methods: {
        close() {
            this.$router.push("home");
        }
    }
};
</script>
<style lang="css">
#newWindow {
    width: 100%;
    height: 240px;
    position: relative;
    left: 50%;
    display: flex;
    align-self: center;
}

#newWindow ul {
    margin: 0;
    padding: 0;
    padding-top: 12px;
}

#newWindow ul li {
    display: inline-block;
    list-style-type: none;
}

#newWindow .newWindow__control-box {
    position: absolute;
    top: -16px;
    right: 10px;
    text-align: right;
    width: 24px;
    height: 24px;
}

#newWindow label {
    font: menu;
    display: inline-block;
    width: 64px;
}

#newWindow .newWindow__control-box i:hover {
    color: var(--dark-selection-color);
}

#newWindow input {
    width: 60%;
}

#newWindow .panel {
    position: absolute;
    right: 0;
    bottom: 0;
    margin-bottom: 20px;
    margin-right: 20px;
}

#newWindow button {
    background-color: var(--dark-title-color);
    border: 1px solid var(--dark-border-color);
}
</style>

// renderer/components/window/NewWindow.tsx
import { useState } from "react";
import { BaseWindowFrame } from "./BaseWindowFrame";

type Project = {
    path: FileList;
    author: string;
};

export function NewWindow(children?: React.ReactNode) {
    const [project, setProject] = useState<Project>({
        path: Array.from([])[0],
        author: "",
    });

    const onFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        project.path = e.target.files;
    };

    return (
        <BaseWindowFrame props={{ width: 256, height: 256 }}>
            <div className="newContainer">
                <div id="newWindow" window-name="게임 속성" ref="newWindow">
                    <ul>
                        <li>
                            <label htmlFor="name">게임명 : </label>
                            <input
                                type="text"
                                placeholder="name"
                                v-model="title"
                            />
                        </li>
                        <li>
                            <label htmlFor="name">위치 : </label>
                            <input
                                type="file"
                                placeholder=""
                                multiple
                                onChange={onFileChange}
                            />
                        </li>
                        <li>
                            <label htmlFor="name">작성자 명 : </label>
                            <input
                                type="text"
                                placeholder=""
                                v-model="project.author"
                            />
                        </li>
                    </ul>
                    <div className="newWindow__control-box">
                        <p>
                            <span>
                                <i
                                    className="far fa-window-close"
                                    id="action-close"
                                    onClick={close}
                                ></i>
                            </span>
                        </p>
                    </div>
                    <div className="panel">
                        <button>
                            <i className="fas fa-upload"></i>프로젝트 생성
                        </button>
                    </div>
                </div>
            </div>
        </BaseWindowFrame>
    );
}
