// renderer/components/window/BaseWindowFrame.tsx
import { ReactSVG, useEffect, useState } from "react";
import styles from "./BaseWindowFrame.module.css";
import Draggable from "react-draggable";
import styled from "styled-components";
import { useRouter } from "next/dist/client/router";

const WindowFrameHeader = styled.div`
    width: ${(props) => props.theme.width + "px"};
    height: ${(props) => props.theme.width + "px"};
    position: relative;
    left: 50%;
    display: flex;
    align-self: center;
    background-color: #252526;
`;

export type ReactBaseWindowLayoutProps = {
    children: React.ReactNode;
    props: {
        width: number;
        height: number;
    };
};

export function BaseWindowFrame({
    children,
    props,
}: ReactBaseWindowLayoutProps) {
    const [name, setName] = useState("");

    const [title, setTitle] = useState("");
    const [isActive, setIsActive] = useState(true);
    const [theme, setTheme] = useState({
        width: props.width,
        height: props.height,
    });

    const router = useRouter();

    const goToHome = () => {
        router.push("/");
    };

    useEffect(() => {});

    return (
        <Draggable grid={[16, 16]}>
            <div className={styles.background}>
                <WindowFrameHeader theme={theme}>
                    <p>
                        <span>
                            <i
                                className="far fa-window-close"
                                onClick={goToHome}
                            />
                        </span>
                    </p>
                    부모 창의 헤더
                </WindowFrameHeader>
                <div className="window-frame-body">
                    <div data-name="content">{children}</div>
                </div>
            </div>
        </Draggable>
    );
}

//

// packages/views/components/window/BaseWindowFrame.vue
<template>
    <div class="window-frame-wrapper" :ref="name">
        <!-- prettier-ignore -->
        <window-frame-header :theme="{
            width: width,
            height: 256,
            }">
            <p>
                <span>
                    <i class="far fa-window-close" @click="close" />
                </span>
            </p>
            부모 창의 헤더
        </window-frame-header>
        <div class="window-frame-body">
            <slot name="content">
                <!-- 여기에 창 내용이 삽입됩니다 -->
            </slot>
        </div>
    </div>
</template>
<script>
import styled from "vue-styled-components";

const WindowFrameHeader = styled.div`
    width: ${props => props.theme.width}px;
    height: 200px;
    position: relative;
    left: 50%;
    display: flex;
    align-self: center;
    background-color: #007acc;
`;

export default {
    components: {
        WindowFrameHeader
    },
    props: {
        name: {
            type: String,
            default: "Window"
        },
        width: {
            type: Number,
            default: 256
        },
        height: {
            type: Number,
            default: 256
        }
    },
    mounted() {
        const refName = this.name;
        $(this.$refs[refName]).draggable();
    },
    data() {
        return {
            title: "",
            isActive: true
        };
    },
    methods: {
        close() {
            this.$router.push("home");
        }
    }
};
</script>
<style lang="scss"></style>
