// packages/renderer/src/components/window/NewWindow.tsx
import { useMemo, useState } from 'react';
import { useClose as useClose } from '@hooks/useClose';
import { BaseWindowFrame } from './BaseWindowFrame';
import { useUUID } from '@hooks/useUUID';
import styled from 'styled-components';

export type Project = {
    path: FileList;
    author: string;
};

export type HTMLInputEvent = React.ChangeEvent<HTMLInputElement>;
export interface WindowRect {
    width: number;
    height: number;
}

const ControlBox = styled.div`
    position: absolute;
    top: -1.5em;
    right: 0;
`;

export default function NewWindow() {
    const { close } = useClose();
    const [gameName, setGameName] = useState('');
    const [, setFileName] = useState('');
    const [listKeys] = useState<string[]>([
        useUUID('newWindow_gameFile')[1],
        useUUID('newWindow_selectFolder')[1],
    ]);

    const windowRect = useMemo(() => {
        return {
            width: 200,
            height: 150,
        };
    }, []) as WindowRect;

    const onChangeGameName = (e: HTMLInputEvent) => {
        setGameName(e.target.value);
    };

    const onChangeFileName = (e: HTMLInputEvent) => {
        setFileName(e.target.value);
    };

    return (
        <BaseWindowFrame props={windowRect}>
            <div className="newContainer">
                <div id="newWindow" window-name={'새로운 프로젝트 생성'}>
                    <ul>
                        <li key={listKeys[0]} className="title">
                            <label htmlFor="name">게임 이름</label>
                            <input
                                type="text"
                                placeholder="게임 이름을 입력하세요."
                                value={gameName}
                                onChange={onChangeGameName}
                            />
                        </li>
                        <li key={listKeys[1]}>
                            <label htmlFor="name">폴더 선택</label>
                            <input
                                type="file"
                                placeholder=""
                                accept="directory"
                                onChange={onChangeFileName}
                            />
                        </li>
                    </ul>
                    <ControlBox>
                        <p>
                            <span>
                                <i
                                    className="far fa-window-close"
                                    id="action-close"
                                    onClick={close}
                                ></i>
                            </span>
                        </p>
                    </ControlBox>
                    <div className="panel">
                        <button>
                            <i className="fas fa-upload"></i>
                            프로젝트 생성하기
                        </button>
                    </div>
                </div>
            </div>
        </BaseWindowFrame>
    );
}

// packages/views/components/window/NewWindow.vue
<template>
    <base-window-frame name="newFileWindow">
        <template #content>
            <div class="newContainer">
                <div id="newWindow" window-name="게임 속성" ref="newWindow">
                    <ul>
                        <li>
                            <label for="name">게임명 : </label
                            ><input
                                type="text"
                                placeholder="name"
                                v-model="title"
                            />
                        </li>
                        <li>
                            <label for="name">위치 : </label
                            ><input
                                type="file"
                                placeholder=""
                                webkitdirectory
                                directory
                                multiple
                                @change="onFileChange($event)"
                            />
                        </li>
                        <li>
                            <label for="name">작성자 명 : </label
                            ><input
                                type="text"
                                placeholder=""
                                v-model="project.author"
                            />
                        </li>
                    </ul>
                    <div class="newWindow__control-box">
                        <p>
                            <span
                                ><i
                                    class="far fa-window-close"
                                    id="action-close"
                                    @click="close"
                                ></i
                            ></span>
                        </p>
                    </div>
                    <div class="panel">
                        <button>
                            <i class="fas fa-upload"></i>프로젝트 생성
                        </button>
                    </div>
                </div>
            </div>
        </template>
    </base-window-frame>
</template>
<script>
import BaseWindowFrame from "./BaseWindowFrame.vue";
export default {
    components: {
        BaseWindowFrame
    },
    data() {
        return {
            title: "",
            project: {
                path: [],
                author: ""
            }
        };
    },
    mounted() {
        $(this.$refs.newWindow).draggable();
    },
    methods: {
        close() {
            this.$router.push("home");
        },
        onFileChange(e) {
            this.project.path = e.target.files;
            console.log(e.target.files);
        }
    }
};
</script>
<style lang="css">
#newWindow {
    width: 256px;
    height: 240px;
    position: relative;
    left: 50%;
    display: flex;
    align-self: center;
}

#newWindow ul {
    margin: 0;
    padding: 0;
    padding-top: 12px;
}

#newWindow ul li {
    display: inline-block;
    list-style-type: none;
}

#newWindow .newWindow__control-box {
    position: absolute;
    top: -16px;
    right: 10px;
    text-align: right;
    width: 24px;
    height: 24px;
}

#newWindow label {
    font: menu;
    display: inline-block;
    width: 64px;
}

#newWindow .newWindow__control-box i:hover {
    color: var(--dark-selection-color);
}

#newWindow input {
    width: 60%;
}

#newWindow .panel {
    position: absolute;
    right: 0;
    bottom: 0;
    margin-bottom: 20px;
    margin-right: 20px;
}

#newWindow button {
    background-color: var(--dark-title-color);
    border: 1px solid var(--dark-border-color);
}
</style>
