// packages/views/components/menu/menuItems/GameMenuItem.vue
<template>
    <ul class="menu__game-sub menu-style" value="Game">
        <li data-action="game-playtest">
            <i class="fas fa-gamepad"></i>Playtest<em>F12</em>
        </li>
        <li class="menu__empty-line"></li>
        <li data-action="game-fullscreen">Launch in Full Screen</li>
        <li data-action="game-show-console">Show Console</li>
        <li data-action="game-folder-open">
            <i class="fas fa-folder-open"></i>Open Game Folder
        </li>
    </ul>
</template>
<script>
export default {};
</script>
<style></style>

// renderer/components/menu/menuItems/GameMenuItem.tsx
export function GameMenuItem() {
    return (
        <ul className="menu__game-sub menu-style" defaultValue="Game">
            <li data-action="game-playtest">
                <i className="fas fa-gamepad"></i>Playtest<em>F12</em>
            </li>
            <li className="menu__empty-line"></li>
            <li data-action="game-fullscreen">Launch in Full Screen</li>
            <li data-action="game-show-console">Show Console</li>
            <li data-action="game-folder-open">
                <i className="fas fa-folder-open"></i>Open Game Folder
            </li>
        </ul>
    );
}
