// packages/views/components/menu/menuItems/ScaleMenuItem.vue
<template>
    <ul class="menu__scale-sub menu-style" value="Scale">
        <li data-action="scale-1x"><i class="fas fa-search-plus"></i>1:1</li>
        <li data-action="scale-2x"><i class="fas fa-search-plus"></i>1:2</li>
        <li data-action="scale-4x"><i class="fas fa-search-plus"></i>1:4</li>
        <li data-action="scale-8x"><i class="fas fa-search-plus"></i>1:8</li>
    </ul>
</template>
<script>
export default {};
</script>
<style></style>

// renderer/components/menu/menuItems/ScaleMenuItem.tsx
import { IconItem } from "@components/atomics/IconItem";
import { ListContainer } from "@components/atomics/ListContainer";
import { ListItem } from "@components/atomics/ListItem";

export function ScaleMenuItem() {
    return (
        <ListContainer
            className="menu__scale-sub menu-style"
            defaultValue="Scale"
        >
            <ListItem data-action="scale-1x">
                <IconItem className="fas fa-search-plus"></IconItem>1:1
            </ListItem>
            <ListItem data-action="scale-2x">
                <IconItem className="fas fa-search-plus"></IconItem>1:2
            </ListItem>
            <ListItem data-action="scale-4x">
                <IconItem className="fas fa-search-plus"></IconItem>1:4
            </ListItem>
            <ListItem data-action="scale-8x">
                <IconItem className="fas fa-search-plus"></IconItem>1:8
            </ListItem>
        </ListContainer>
    );
}
