// packages/views/components/TileSelectWindow.vue
<template>
    <div id="aside">
        <div class="aside__tabs">
            <div id="view" ondragstart="return false;"></div>
            <!-- 탭 컨트롤을 위한 체크박스입니다. -->
            <input type="radio" name="tile" id="a" checked />
            <input type="radio" name="tile" id="b" />
            <input type="radio" name="tile" id="c" />
            <input type="radio" name="tile" id="d" />
            <input type="radio" name="tile" id="e" />
            <ul>
                <li>
                    <label for="a" id="tab-a" data-action="tab1">A</label>
                </li>
                <li>
                    <label for="b" id="tab-b" data-action="tab2">B</label>
                </li>
                <li>
                    <label for="c" id="tab-c" data-action="tab3">C</label>
                </li>
                <li>
                    <label for="d" id="tab-d" data-action="tab4">D</label>
                </li>
                <li>
                    <label for="e" id="tab-e" data-action="tab5">E</label>
                </li>
            </ul>
            <div class="aside__tabs__maptree">
                <ul>
                    <li>
                        <i class="fas fa-folder"></i>레이어 그룹
                        <ul class="aside__tabs__maptree-child-tree">
                            <li data-action="layer1">
                                <i class="far fa-eye"></i>레이어 1
                            </li>
                            <li data-action="layer2">
                                <i class="far fa-eye"></i>레이어 2
                            </li>
                            <li data-action="layer3">
                                <i class="far fa-eye"></i>레이어 3
                            </li>
                            <li data-action="layer4">
                                <i class="far fa-eye"></i>레이어 4
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</template>
<script>
export default {};
</script>
<style></style>

// packages/renderer/src/components/frame/TileSelectWindow.tsx
import { Label } from "../atomics/Label";
import { IconItem } from "../atomics/IconItem";
import { Input } from "../atomics/Input";
import { ListContainer } from "../atomics/ListContainer";
import { ListItem } from "../atomics/ListItem";
import { Division } from "../atomics/Wrapper";
import { TilesetMarker } from "./TilesetMarker";

export function TileSelectWindow() {
  return (
    <Division id="aside">
      <Division className="aside__tabs">
        <Division id="view" onDragStart={() => false}></Division>
        <TilesetMarker />

        <Input type="radio" name="tile" id="a" defaultChecked />
        <Input type="radio" name="tile" id="b" />
        <Input type="radio" name="tile" id="c" />
        <Input type="radio" name="tile" id="d" />
        <Input type="radio" name="tile" id="e" />
        <ListContainer>
          <ListItem key="x1e4_tileset_window_tab_1">
            <Label htmlFor="a" id="tab-a" data-action="tab1">
              A
            </Label>
          </ListItem>
          <ListItem key="x1e4_tileset_window_tab_2">
            <Label htmlFor="b" id="tab-b" data-action="tab2">
              B
            </Label>
          </ListItem>
          <ListItem key="x1e4_tileset_window_tab_3">
            <Label htmlFor="c" id="tab-c" data-action="tab3">
              C
            </Label>
          </ListItem>
          <ListItem key="x1e4_tileset_window_tab_4">
            <Label htmlFor="d" id="tab-d" data-action="tab4">
              D
            </Label>
          </ListItem>
          <ListItem key="x1e4_tileset_window_tab_5">
            <Label htmlFor="e" id="tab-e" data-action="tab5">
              E
            </Label>
          </ListItem>
        </ListContainer>
        <Division className="aside__tabs__maptree">
          <ListContainer>
            <ListItem>
              <IconItem className="fas fa-folder" />
              레이어 그룹
              <ListContainer className="aside__tabs__maptree-child-tree">
                <ListItem
                  data-action="layer1"
                  key="x1e4_tileset_window_map_tree_layer_1"
                >
                  <IconItem className="far fa-eye" />
                  레이어 1
                </ListItem>
                <ListItem
                  data-action="layer2"
                  key="x1e4_tileset_window_map_tree_layer_2"
                >
                  <IconItem className="far fa-eye" />
                  레이어 2
                </ListItem>
                <ListItem
                  data-action="layer3"
                  key="x1e4_tileset_window_map_tree_layer_3"
                >
                  <IconItem className="far fa-eye" />
                  레이어 3
                </ListItem>
                <ListItem
                  data-action="layer4"
                  key="x1e4_tileset_window_map_tree_layer_4"
                >
                  <IconItem className="far fa-eye" />
                  레이어 4
                </ListItem>
              </ListContainer>
            </ListItem>
          </ListContainer>
        </Division>
      </Division>
    </Division>
  );
}
