// packages/views/components/window/BaseWindowFrame.vue
<template>
    <div class="window-frame-wrapper" :ref="name">
        <!-- prettier-ignore -->
        <window-frame-header :theme="{
            width: width,
            height: 256,
            }">
            <p>
                <span>
                    <i class="far fa-window-close" @click="close" />
                </span>
            </p>
            부모 창의 헤더
        </window-frame-header>
        <div class="window-frame-body">
            <slot name="content">
                <!-- 여기에 창 내용이 삽입됩니다 -->
            </slot>
        </div>
    </div>
</template>
<script>
import styled from "vue-styled-components";

const WindowFrameHeader = styled.div`
    width: ${props => props.theme.width}px;
    height: 200px;
    position: relative;
    left: 50%;
    display: flex;
    align-self: center;
    background-color: #007acc;
`;

export default {
    components: {
        WindowFrameHeader
    },
    props: {
        name: {
            type: String,
            default: "Window"
        },
        width: {
            type: Number,
            default: 256
        },
        height: {
            type: Number,
            default: 256
        }
    },
    mounted() {
        const refName = this.name;
        $(this.$refs[refName]).draggable();
    },
    data() {
        return {
            title: "",
            isActive: true
        };
    },
    methods: {
        close() {
            this.$router.push("home");
        }
    }
};
</script>
<style lang="scss"></style>

// packages/initial-editor/renderer/components/window/BaseWindowFrame.tsx
import { useState } from "react";
import Draggable from "react-draggable";
import styled from "styled-components";
import { Division } from "@components/atomics/Wrapper";
import { Paragraph } from "@components/atomics/Paragraph";
import classNames from "classnames";

const WindowFrameHeader = styled.div`
    width: ${(props) => props.theme.width + "px"};
    height: ${(props) => props.theme.height + "px"};
    position: relative;
    left: 50%;
    display: flex;
    align-self: center;
`;

export type ReactBaseWindowLayoutProps = {
    children: React.ReactNode;
    props: {
        width: number;
        height: number;
    };
};

const BaseWindowFrameWrapper = styled.div`
    .background {
        width: 100%;
        height: 100%;
        position: relative;
        left: 50%;
        display: flex;
        align-self: center;
    }

    .windowFrameBody {
        height: 2.5em;
        line-height: 2.5em;
    }
`;

export function BaseWindowFrame({
    children,
    props,
}: ReactBaseWindowLayoutProps) {
    const [theme] = useState({
        width: props.width,
        height: props.height,
    });

    return (
        <BaseWindowFrameWrapper>
            <Draggable grid={[16, 16]}>
                <Division className={classNames(`background`)}>
                    <WindowFrameHeader theme={theme}>
                        <Paragraph></Paragraph>
                    </WindowFrameHeader>
                    <Division className={classNames("windowFrameBody")}>
                        <Division data-name="content">{children}</Division>
                    </Division>
                </Division>
            </Draggable>
        </BaseWindowFrameWrapper>
    );
}
