// packages/initial-editor/renderer/components/menu/menuItems/DrawMenuItem.tsx
import { IconItem } from "@components/atomics/IconItem";
import { ListContainer } from "@components/atomics/ListContainer";
import { ListItem } from "@components/atomics/ListItem";

export function DrawMenuitem() {
    return (
        // ul을 컴포넌트로 감싸면 유니크 클래스 명이 생성되는 듯 하다.
        <ul className="menu__draw-sub menu-style" defaultValue="Draw">
            <li data-action="draw-pencil" key="draw-pencil_x1r1">
                <i className="fas fa-pencil-alt" />
                Pencil
            </li>
            <li data-action="draw-rectangle" key="draw-rectangle_x1r1">
                <i className="fas fa-square-full" />
                Rectangle
            </li>
            <li data-action="draw-ellipse" key="draw-ellipse_x2r2">
                <i className="fas fa-circle" />
                Ellipse
            </li>
            <li data-action="draw-flood-fill" key="draw-flood-fill_x2r2">
                <i className="fas fa-fill" />
                Flood Fill
            </li>
            <li data-action="draw-shadow-pen" key="draw-shadow-pen_x3r3">
                <i className="fas fa-paint-brush" />
                Shadow Pen
            </li>
        </ul>
    );
}

// packages/views/components/menu/menuItems/DrawMenuItem.vue
<template>
    <ul class="menu__draw-sub menu-style" value="Draw">
        <li data-action="draw-pencil">
            <i class="fas fa-pencil-alt"></i>Pencil
        </li>
        <li data-action="draw-rectangle">
            <i class="fas fa-square-full"></i>Rectangle
        </li>
        <li data-action="draw-ellipse"><i class="fas fa-circle"></i>Ellipse</li>
        <li data-action="draw-flood-fill">
            <i class="fas fa-fill"></i>Flood Fill
        </li>
        <li data-action="draw-shadow-pen">
            <i class="fas fa-paint-brush"></i>Shadow Pen
        </li>
    </ul>
</template>
<script>
export default {};
</script>
