// renderer/components/menu/menuItems/HelpMenuItem.tsx
export function HelpMenuItem() {
    return (
        <ul className="menu__help-sub menu-style" defaultValue="Help">
            <li data-action="help-contents">
                <i className="fas fa-question-circle"></i>Contents<em>F1</em>
            </li>
            <li className="menu__empty-line"></li>
            <li data-action="help-about">
                <i className="fas fa-info-circle"></i>About...
            </li>
        </ul>
    );
}

// packages/views/components/menu/menuItems/HelpMenuItem.vue
<template>
    <ul class="menu__help-sub menu-style" value="Help">
        <li data-action="help-contents">
            <i class="fas fa-question-circle"></i>Contents<em>F1</em>
        </li>
        <li class="menu__empty-line"></li>
        <li data-action="help-about">
            <i class="fas fa-info-circle"></i>About...
        </li>
    </ul>
</template>
<script>
export default {};
</script>
<style></style>
