// packages/views/components/menu/menuItems/EditMenuItem.vue
<template>
    <ul class="menu__edit-sub menu-style" value="Edit">
        <li data-action="edit-undo"><i class="fas fa-undo"></i>Undo</li>
        <li class="menu__empty-line"></li>
        <li data-action="edit-cut"><i class="fas fa-cut"></i>Cut</li>
        <li data-action="edit-copy"><i class="fas fa-copy"></i>Copy</li>
        <li data-action="edit-paste"><i class="fas fa-paste"></i>Paste</li>
        <li data-action="edit-delete">
            <i class="fas fa-trash-alt"></i>Delete
        </li>
    </ul>
</template>
<script>
export default {};
</script>
<style></style>

// packages/initial-editor/renderer/components/menu/menuItems/EditMenuItem.tsx
import { IconItem } from "@components/atomics/IconItem";
import { ListItem } from "@components/atomics/ListItem";
import { ListContainer } from "../../atomics/ListContainer";

export function EditMenuItem() {
    return (
        <ul className="menu__edit-sub menu-style" defaultValue="Edit">
            <li data-action="edit-undo">
                <i className="fas fa-undo"></i>Undo
            </li>
            <li className="menu__empty-line"></li>
            <li data-action="edit-cut">
                <i className="fas fa-cut"></i>Cut
            </li>
            <li data-action="edit-copy">
                <i className="fas fa-copy"></i>Copy
            </li>
            <li data-action="edit-paste">
                <i className="fas fa-paste"></i>Paste
            </li>
            <li data-action="edit-delete">
                <i className="fas fa-trash-alt"></i>Delete
            </li>
        </ul>
    );
}
