// packages/views/components/menu/menuItems/ModeMenuItem.vue
<template>
    <ul class="menu__mode-sub menu-style" value="Mode">
        <li data-action="mode-map"><i class="fas fa-layer-group"></i>Map</li>
        <li data-action="mode-event">
            <i class="fas fa-flag-checkered"></i>Event
        </li>
        <li data-action="mode-region"><i class="fas fa-map"></i>Region</li>
    </ul>
</template>
<script>
export default {};
</script>

// legacy/renderer/src/components/menu/menuItems/ModeMenuItem.tsx
export function ModeMenuItem() {
  return (
    <ul className="menu__mode-sub menu-style" defaultValue="Mode">
      <li data-action="mode-map">
        <i className="fas fa-layer-group"></i>Map
      </li>
      <li data-action="mode-event">
        <i className="fas fa-flag-checkered"></i>Event
      </li>
      <li data-action="mode-region">
        <i className="fas fa-map"></i>Region
      </li>
    </ul>
  );
}
